### ISSUE TITLE
Feature request: Console commands

### ISSUE THREAD

**Issue by SlimeDog** [SouthplexStudio/CommandBridge#3]
CommandBridge 1.1-BETA

Please implement console commands. Most commands are useful from the console.

**Comment by jingwenMC** [comment]
Can you describe the feature more clearly?

**Comment by SlimeDog** [comment]
As an example
> tempban <player> 1d

execute on the BungeeCord console, should ban the player. Maybe it does, but was just conflated with #4

**Comment by jingwenMC** [comment]
I will try to figure it out and make an update soon.

**Comment by jingwenMC** [comment]
Solved in the latest commit

**Comment by jingwenMC** [comment]
Duplicated with #4
