### ISSUE TITLE
Commands do not execute

### ISSUE THREAD

**Issue by SlimeDog** [SouthplexStudio/CommandBridge#4]
Waterfall 1.17-448
Spigot 1.17.1-3203
CommandBridge 1.1-BETA

Commands executed by a player on Spigot server are logged on the Spigot server, but are not executed on the Waterfall server. There are no errors logged on either server, or displayed in-game to the player.

**Comment by jingwenMC** [comment]
I will try to fix it in the next version using a new way to make connection between Bungee and Bukkit

**Comment by SlimeDog** [comment]
That would be nice, given that is the whole purpose of the resource.

**Comment by jingwenMC** [comment]
Solved in latest commit

**Comment by SlimeDog** [comment]
Nice. Are there builds to test?

**Comment by jingwenMC** [comment]
Here's one:https://drive.google.com/file/d/1nQ1gtC6jpdxlGMWPaWereSkNGwQAHR-G/view?usp=sharing

**Comment by SlimeDog** [comment]
Thanks. That's the spigot resource. And the bungee one?

**Comment by jingwenMC** [comment]
Bungee side has nothing changed for now

**Comment by SlimeDog** [comment]
OK, thanks.

**Comment by SlimeDog** [comment]
Commands still do not execute at console. See #5
