### ISSUE TITLE
Start-up failure on BungeeCord

### ISSUE THREAD

**Issue by SlimeDog** [SouthplexStudio/CommandBridge#7]
BungeeCord-Bootstrap:1.17-R0.1-SNAPSHOT:bda1605:1598
CommandBridge-bungeecord-1.2-BETA

On proxy start-up:
```
10:13:14 [INFO] [CommandBridge] [CommandBridge]Setting Up...
10:13:14 [WARNING] Exception encountered when loading plugin: CommandBridge
java.lang.NoClassDefFoundError: top/jingwenmc/mqeasy/api/plugin/MQEasyPlugin
    at cn.southplex.commandbridge.CommandBridgeBungee.checkRunningMode(CommandBridgeBungee.java:69)
    at cn.southplex.commandbridge.CommandBridgeBungee.onEnable(CommandBridgeBungee.java:39)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:287)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: top.jingwenmc.mqeasy.api.plugin.MQEasyPlugin
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:97)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
    ... 6 more
```

**Comment by jingwenMC** [comment]
Are you using "MessageQueue" mode?

**Comment by SlimeDog** [comment]
Of course.
```
#Running Modes:
#- PluginMessage (Outdated,will be REMOVED in 2.0)
#- MessageQueue (Recommended,using external plugin MQEasy)
```

config.yml
```
# CommandBridge Config File

# This field is to recognize the config version
# DO NOT EDIT AT ANY TIME
version: 1c

# This is the password field
# You need to set to a different value for security reason
# You need it to send a command, see https://github.com/SouthplexStudio/CommandBridge/wiki/FAQ:-How-to-send-a-command-to-BungeeCord
password: GoodDog

#Running Modes:
#- PluginMessage (Outdated,will be REMOVED in 2.0)
#- MessageQueue (Recommended,using external plugin MQEasy)
#MQEasy Installation: https://github.com/jingwenMC/MQEasy/wiki/Installation
#NOTE: PluginMessage Mode only support Bukkit->Bungee.
running-mode: MessageQueue

#Allows player (with permission "commandbridge.bukkit.send",or OP) to execute command in game
enable-player-command: true
```

**Comment by jingwenMC** [comment]
Using "MessageQueue" mode requires a dependency called "MQEasy"
It's available at https://www.spigotmc.org/resources/mqeasy-messaging-api-1-8-1-17-x.95415/

**Comment by SlimeDog** [comment]
I missed that. :(

I would be good to state on the Overview page that there is a dependency.

**Comment by SlimeDog** [comment]
I will use PluginMessage for now.

Please better document the configuration options for both CommandBridge and MQEasy. In particular, why I would chose one option over another, whether network ports need to be opened (network administrators care), etc.

**Comment by jingwenMC** [comment]
OK, I will update the documentation later.



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 18, 2021 13:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SouthplexStudio/CommandBridge] Start-up failure on BungeeCord (#7)




 
I will use PluginMessage for now.
 
Please better document the configuration options for both CommandBridge and MQEasy. In particular, why I would chose one option over another, whether network ports need to be opened (network administrators care), etc.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
